import type { ReactNode } from "react";
import { MessageSquareQuote, ThumbsUp, Clock } from "lucide-react";
import { 
  SHARE_CARD_CONFIG, 
  formatTimestamp, 
  getScoreColor,
  type AspectRatio 
} from "@/lib/shareCards";

export interface AnnotationCardData {
  id: string;
  text: string;
  content: string | null;
  timestamp: number | null;
  authorName: string | null;
  upvotes: number;
  episode: {
    id: string;
    title: string;
    artworkUrl: string | null;
  };
  podcast: {
    id: string;
    title: string;
    artworkUrl: string | null;
  };
}

export interface IntegrityCardData {
  episodeId: string;
  episodeTitle: string;
  podcastTitle: string | null;
  artworkUrl: string | null;
  integrityScore: number;
  transcriptConsistency: number | null;
  addedCount: number;
  removedCount: number;
  modifiedCount: number;
  sponsorCount: number;
  claims: {
    total: number;
    financial: number;
    medical: number;
    sensitive: number;
    highRisk: number;
    riskLevel: "low" | "medium" | "high";
  };
}

interface BaseCardProps {
  aspectRatio?: AspectRatio;
  className?: string;
}

const { theme, brand, typography } = SHARE_CARD_CONFIG;

function CardContainer({ 
  children, 
  aspectRatio = "portrait",
  variant = "default",
  className = "",
}: { 
  children: ReactNode; 
  aspectRatio?: AspectRatio;
  variant?: "default" | "integrity";
  className?: string;
}) {
  const aspectClass = aspectRatio === "portrait" 
    ? "aspect-[4/5]" 
    : aspectRatio === "square" 
    ? "aspect-square" 
    : "aspect-[4/5] md:aspect-[4/3]";
    
  const bgGradient = variant === "integrity" 
    ? theme.background.integrity 
    : theme.background.primary;
    
  const maxWidth = variant === "integrity"
    ? "max-w-[600px] md:max-w-[800px] lg:max-w-[1080px]"
    : "max-w-[500px] md:max-w-[600px]";

  return (
    <div
      className={`
        w-full ${maxWidth}
        ${aspectClass}
        bg-gradient-to-br ${bgGradient}
        rounded-3xl ${theme.border} shadow-2xl
        flex flex-col p-6 md:p-8
        ${className}
      `}
    >
      {children}
    </div>
  );
}

function PodcastArtwork({ 
  src, 
  alt, 
  size = "medium" 
}: { 
  src: string | null; 
  alt: string;
  size?: "small" | "medium" | "large";
}) {
  const sizeClasses = {
    small: "w-12 h-12 md:w-14 md:h-14 rounded-xl",
    medium: "w-20 h-20 md:w-28 md:h-28 rounded-2xl",
    large: "w-24 h-24 md:w-32 md:h-32 rounded-2xl",
  };

  return (
    <div className={`${sizeClasses[size]} bg-zinc-900 overflow-hidden flex-shrink-0`}>
      {src ? (
        <img
          src={src}
          alt={alt}
          className="w-full h-full object-cover"
          data-testid="img-podcast-artwork"
        />
      ) : (
        <div className="w-full h-full flex items-center justify-center text-[8px] text-zinc-500">
          POD<br />DNA
        </div>
      )}
    </div>
  );
}

function BrandFooter({ variant = "simple" }: { variant?: "simple" | "detailed" }) {
  if (variant === "detailed") {
    return (
      <div className="mt-auto flex items-center justify-between pt-3 md:pt-4 border-t border-white/5">
        <p className="text-[10px] md:text-[11px] text-zinc-500">
          Snapshot generated by {brand.name}'s Podcast Integrity Engine.
        </p>
        <div className="text-[10px] md:text-[11px] text-zinc-500 flex items-center gap-2">
          <span className="h-4 w-4 md:h-5 md:w-5 rounded-full border border-zinc-600 flex items-center justify-center text-[8px] md:text-[10px] font-medium">
            P
          </span>
          <span>{brand.domain}</span>
        </div>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-2">
      <span className="text-[10px] uppercase tracking-widest text-zinc-600">via</span>
      <span className={`text-xs font-semibold ${brand.colors.primary}`}>{brand.name}</span>
    </div>
  );
}

export function AnnotationShareCard({ 
  data, 
  aspectRatio = "portrait",
  className = "",
}: BaseCardProps & { data: AnnotationCardData }) {
  const artworkUrl = data.episode.artworkUrl || data.podcast.artworkUrl;

  return (
    <CardContainer aspectRatio={aspectRatio} className={className}>
      <div className="flex justify-center mb-4">
        <MessageSquareQuote className={`w-8 h-8 ${theme.text.accent} opacity-60`} />
      </div>

      <div className="flex-1 flex flex-col justify-center">
        <blockquote className="text-center">
          <p
            className={`${typography.quote.medium} font-medium leading-relaxed text-white/95`}
            data-testid="text-annotation-quote"
          >
            "{data.text}"
          </p>
        </blockquote>

        {data.content && (
          <p
            className={`text-center ${typography.caption} ${theme.text.secondary} mt-4 italic`}
            data-testid="text-annotation-content"
          >
            {data.content}
          </p>
        )}
      </div>

      <div className="w-16 h-px bg-gradient-to-r from-transparent via-zinc-600 to-transparent mx-auto my-4" />

      <div className="flex items-center gap-3">
        <PodcastArtwork src={artworkUrl} alt={data.podcast.title} size="small" />
        <div className="flex-1 min-w-0">
          <p className={`${typography.caption} font-medium text-white/90 line-clamp-1`} data-testid="text-episode-title">
            {data.episode.title}
          </p>
          <p className={`${typography.micro} ${theme.text.tertiary} line-clamp-1`} data-testid="text-podcast-title">
            {data.podcast.title}
          </p>
        </div>
      </div>

      <div className={`flex items-center justify-between mt-4 pt-4 ${theme.divider} border-t`}>
        <div className={`flex items-center gap-4 ${typography.micro} ${theme.text.tertiary}`}>
          {data.timestamp !== null && (
            <span className="flex items-center gap-1">
              <Clock className="w-3 h-3" />
              {formatTimestamp(data.timestamp)}
            </span>
          )}
          {data.upvotes > 0 && (
            <span className="flex items-center gap-1">
              <ThumbsUp className="w-3 h-3" />
              {data.upvotes}
            </span>
          )}
        </div>
        <BrandFooter variant="simple" />
      </div>
    </CardContainer>
  );
}

function MetricPill({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col gap-1 bg-white/5 border border-white/10 rounded-xl px-2 md:px-3 py-2">
      <span className={`text-[9px] md:text-[10px] uppercase ${typography.tracking} ${theme.text.secondary}`}>
        {label}
      </span>
      <span className="text-xs md:text-sm text-zinc-100 truncate">{value}</span>
    </div>
  );
}

function BreakdownCard({ 
  title, 
  items 
}: { 
  title: string; 
  items: { label: string; value: string | number }[];
}) {
  return (
    <div className="bg-white/5 border border-white/10 rounded-2xl px-3 py-3 flex flex-col gap-1.5">
      <div className={`text-[10px] md:text-[11px] uppercase ${typography.tracking} ${theme.text.secondary} mb-1`}>
        {title}
      </div>
      {items.map((item) => (
        <div key={item.label} className="flex justify-between text-[10px] md:text-[11px]">
          <span className={theme.text.secondary}>{item.label}</span>
          <span className="text-zinc-100 font-medium">{item.value}</span>
        </div>
      ))}
    </div>
  );
}

export function IntegrityShareCard({ 
  data,
  className = "",
}: BaseCardProps & { data: IntegrityCardData }) {
  return (
    <CardContainer variant="integrity" aspectRatio="landscape" className={`gap-4 md:gap-6 ${className}`}>
      <div className="flex gap-4 md:gap-6 items-center">
        <PodcastArtwork src={data.artworkUrl} alt={data.podcastTitle ?? "Podcast"} size="medium" />
        <div className="flex flex-col gap-1 min-w-0">
          <div className={`${typography.micro} uppercase ${typography.tracking} ${theme.text.secondary}`}>
            {brand.name} · Integrity Snapshot
          </div>
          <h1 className={`${typography.title.medium} font-semibold line-clamp-2`} data-testid="text-episode-title">
            {data.episodeTitle}
          </h1>
          {data.podcastTitle && (
            <p className={`${typography.caption} ${theme.text.secondary} line-clamp-1`} data-testid="text-podcast-title">
              {data.podcastTitle}
            </p>
          )}
        </div>
      </div>

      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 md:gap-6">
        <div className="flex flex-col gap-2">
          <div className={`${typography.micro} uppercase ${typography.tracking} ${theme.text.secondary}`}>
            Integrity Score
          </div>
          <div className="flex items-end gap-3">
            <span
              className={`text-5xl md:text-6xl font-bold ${getScoreColor(data.integrityScore)}`}
              data-testid="text-integrity-score"
            >
              {data.integrityScore}
            </span>
            <span className={`${theme.text.tertiary} mb-1 md:mb-2 text-base md:text-lg`}>/100</span>
          </div>
        </div>

        <div className="flex-1 grid grid-cols-2 gap-2 md:gap-3 text-xs">
          <MetricPill
            label="Transcript Consistency"
            value={
              data.transcriptConsistency != null
                ? `${Math.round(data.transcriptConsistency)}%`
                : "Not analyzed"
            }
          />
          <MetricPill
            label="Changes Detected"
            value={String(data.addedCount + data.removedCount + data.modifiedCount)}
          />
          <MetricPill
            label="Sponsors"
            value={data.sponsorCount > 0 ? `${data.sponsorCount} detected` : "None detected"}
          />
          <MetricPill
            label="Claims Risk"
            value={data.claims.total === 0 ? "No claims" : data.claims.riskLevel.toUpperCase()}
          />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-3 md:gap-4 text-xs mt-2">
        <BreakdownCard
          title="Transcript Changes"
          items={[
            { label: "Added", value: data.addedCount },
            { label: "Removed", value: data.removedCount },
            { label: "Modified", value: data.modifiedCount },
          ]}
        />
        <BreakdownCard
          title="Sponsor Mentions"
          items={[
            { label: "Total", value: data.sponsorCount },
            {
              label: "Coverage",
              value: data.sponsorCount === 0 ? "N/A" : data.sponsorCount <= 2 ? "Focused" : "Heavy",
            },
          ]}
        />
        <BreakdownCard
          title="Claims Overview"
          items={[
            { label: "Total", value: data.claims.total },
            { label: "Financial", value: data.claims.financial },
            { label: "Medical", value: data.claims.medical },
            { label: "Sensitive", value: data.claims.sensitive },
            { label: "High-risk", value: data.claims.highRisk },
          ]}
        />
      </div>

      <BrandFooter variant="detailed" />
    </CardContainer>
  );
}

export type ShareCardType = "annotation" | "integrity";

export function generateShareCard(
  type: ShareCardType,
  data: AnnotationCardData | IntegrityCardData,
  options: { aspectRatio?: AspectRatio; className?: string } = {}
) {
  if (type === "annotation") {
    return <AnnotationShareCard data={data as AnnotationCardData} {...options} />;
  }
  return <IntegrityShareCard data={data as IntegrityCardData} {...options} />;
}
